version: '3.8'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://adm:clave123@cluster0.kw5obel.mongodb.net/taskdb?retryWrites=true&w=majority
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: "mongodb+srv://adm:clave123@cluster0.kw5obel.mongodb.net/taskdb?retryWrites=true&w=majority"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
